nome=input('Qual e seu nome?')
idade=input('Qual e sua idade?')
peso=input('Qual e seu peso?')
print('então seu nome e', [nome])
print('sua idade e', [idade])
print('seu peso e', [peso])
print(' obrigado pela informacao volte sempre :) ')
